package ImageToText.ImageText;

public class postProcess {

	public static void main(String []args) {
		
		String outocr = "Bristol-Myers Squibb\nPatient Assistance Foundation\nPhone: 800-736-0003\nMonday to Friday: 8:00 AM - 8:00 PM ET\n(excluding holidays)\nBMSPAF Case #:\nPO Box 220769, Charlotte, NC 28222-0769 | Phone: 800-736-0003 Fax: 800-736-1611\nAshley Williams\n08 031973\nSection 1: Patient Information\n(TO BE COMPLETED BY PATIENT ALL BOXES ARE REQUIRED EXCEPT WHERE NOTED).\nPatient Name:\nSocial Security Number (Providing SSN is optional).\n5432176543\nDate of Birth:\nGender: O Female O Male\nPatient Address (no PO Boxes).\nCity: London\nState: OH\nZip: 53317\nHome Phone:\nCell Phone (optional):\nEmail Address (optional)\n6153215432\n6153215431\nAlternate Contact Name (optional):\nRelationship (optional)\nPhone (optional):\nBrian Williams\nSpause\n015127 5432\nAllergies (you may attach a list on a separate page it more space is needed):\nashley, Williams@hotmalaa\nAllegra\nAll Current Medications (you may attach a list on a separate page it more space is needed):\nPATIENT INSURANCE INFORMATION - Do vou have insurance through any of these providers?\n(Check all that apply)\nMedicaid\nMedicare: Part A Part B part Part C/Medicare Advantage\nVA or Military\nPrivate Insurance\nNone\nState Assistance Program for Medication\nother: Cigna ABP\nINSURANCE NAME\nPHONE #\nID/POLICY #\nPrimary: Medicaid\nSecondary: Medicare Part D\nPrescription Coverage:\nID/Policy #: 43758912\n(Optional: Attach a copy of both sides of your\nprescription insurance card)\nRxBIN: RxPCN:\nNumber of people living in your home:\n(include yourself, your spouse, and any dependents currently living with you)\nTOTAL YEARLY HOUSEHOLD INCOME:\nOR TOTAL MONTHLY HOUSEHOLD INCOME:\n$ 54,000\ns 5,000\nProof of income may be required: Please provide your most recent federal tax return. If your federal tax return is not available,\nplease provide as many of the following as available: W2, 1099, pension statement, Social Security statement, at least 2 consecutive\npay stubs.\nMedicare Part D recipient: If you have spent 3% of your annual income on out-of-pocket prescription costs, please contact your\npharmacy to provide you with a report to document your yearly out-of-pocket expenses. Report must be attached to this application.\nPlease continue to the next page to read, sign, and date the Patient Agreement & Consent.\nELIQUIS, NULOJIX, and ORENCIA are trademarks of Bristol-Myers Squibb Company.\nNOUS1900997-02 12/19\nDownloaded from NeedyMeds.org\n" ;
		System.out.println(outocr);
	}
}
